# Generated by Django 5.0.2 on 2025-05-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_quest_latitude_quest_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_route_builder",
            field=models.BooleanField(
                default=False, help_text="Может создавать новые маршруты"
            ),
        ),
    ]
