# Generated by Django 5.0.2 on 2025-05-10 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_is_route_builder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RouteQuest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Позиция квеста в маршруте (1, 2, 3…)"
                    ),
                ),
                (
                    "hint_text",
                    models.TextField(blank=True, help_text="Подсказка для точки"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="route_quest_photos/"
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True, null=True, upload_to="route_quest_audio/"
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.quest",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_quests",
                        to="core.route",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "indexes": [
                    models.Index(
                        fields=["route", "order"], name="core_routeq_route_i_77f88d_idx"
                    )
                ],
                "unique_together": {("route", "quest")},
            },
        ),
    ]
